#!/bin/bash
export APPLICATION_NAME=$1
#export APPLICATION_NAME=$(echo $APPLICATION_NAME | perl -pe 's/(^|-)./uc($&)/ge;s/-//g')
export ENVIRONMENT=$2
if [ "$ENVIRONMENT" == "dev" ]
  then
    export NODE_ENV="development"
elif [ "$ENVIRONMENT" == "stg" ]
  then
    export NODE_ENV="staging"
elif [ "$ENVIRONMENT" == "prod" ]
  then
    export NODE_ENV="production"
else
  export NODE_ENV="development"
fi
export NODE_PATH=$NODE_PATH:./framework
export TARGET_ENV=$NODE_ENV
if [ "$ENVIRONMENT" == "dev" ]
  then
    npm run develop
else
  npm run start
fi
